### PR TITLE
Add ease func example in notebook

### PR DESCRIPTION
**Pull request by kolibril13**
This pr adds a notebook with an ease func.
Note that the video output is embedded, so the notebook is quite big (0.3 MB in total)

### CODE REVIEW

**Review by alisterburt — COMMENTED** [review]
Thanks @kolibril13 - could you add this example as .py instead? not a huge fan of notebooks in repos :)

**Comment by kolibril13** [comment]
Yes, I can see your point and I will convert it to .py! :)

Just to defend notebooks a bit:
I think they are absolutely great, even in repos.
And there is even a new GitHub Feature coming soon that will allow rich diff:
image

Also, I think that napari-animation would be amazing to be used in notebooks, as mentioned here: https://github.com/napari/napari-animation/issues/147

**Comment by kolibril13** [comment]
file is not converted.

**Review by alisterburt — APPROVED** [review]
wow, that feature looks awesome!! Thanks for the quick turnaround here

**Pull request merged**
