### PR TITLE
Stylesheet fix

### PR DESCRIPTION
**Pull request by alisterburt**
fix broken plugin import due to deprecation of `qt_viewer.raw_stylesheet` in napari 0.4.8 napari/napari#2643 - fixed by mirroring the napari console implementation
https://github.com/napari/napari-console/blob/fd3a291331e052e591042850b56fd1db5815f784/napari_console/qt_console.py#L151-L171

### CODE REVIEW

**Comment by alisterburt** [comment]
removing extra commit!!

**Comment by sofroniewn** [comment]
This PR also has the skeleton docs, can you remove them, thanks!!

**Comment by sofroniewn** [comment]
Do we need to bump a minimum napari version? or was this in `0.4.5` already? We might need to bump for other reasons, but if not lets leave it

**Comment by sofroniewn** [comment]
Looks like it should have been in 0.4.5 https://github.com/napari/napari/pull/2241

**Comment by alisterburt** [comment]
tested locally and working with 0.4.5! Think we're good to go

**Comment by tlambert03** [comment]
hang on before merging this...  the console repo is not a good one to mimic here... since it needs to do specific things with theming because of upstream QtConsole weirdness.  in almost all cases, the best approach (if possible) is not to set the theme and stylesheet at all, but let it be naturally inherited from the parent.  lemme see if I can try

**Comment by alisterburt** [comment]
good to know, thanks - I think the original theming was done before `provide_dock_widget` so indeed might be unnecessary now!

**Comment by sofroniewn** [comment]
Ok, nice looks like this was all we needed, and we've also fixed the stretch. Will merge now. Thanks all!!

**Comment by tlambert03** [comment]
nooo :joy: ... ok will submit a new PR :)

**Comment by sofroniewn** [comment]
loooooolz

**Comment by sofroniewn** [comment]
> hang on before merging this...

ahhhhhhhh

**Pull request merged**
